name: first_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.6
  fl_chart: ^0.36.1

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/logo.png
    - images/water.png
    - images/aeration.png
    - images/co2.png
    - images/o2.png
    - images/cold.png
    - images/humidity.png
    - images/logo2.png

